/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatIsIDRouteImport } from './routes/watIsID'
import { Route as MainRouteImport } from './routes/main'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as ProjectNameRouteImport } from './routes/project.$name'

const WatIsIDRoute = WatIsIDRouteImport.update({
  id: '/watIsID',
  path: '/watIsID',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectNameRoute = ProjectNameRouteImport.update({
  id: '/project/$name',
  path: '/project/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/articles': typeof ArticlesRoute
  '/main': typeof MainRoute
  '/watIsID': typeof WatIsIDRoute
  '/project/$name': typeof ProjectNameRoute
}
export interface FileRoutesByTo {
  '/articles': typeof ArticlesRoute
  '/main': typeof MainRoute
  '/watIsID': typeof WatIsIDRoute
  '/project/$name': typeof ProjectNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/articles': typeof ArticlesRoute
  '/main': typeof MainRoute
  '/watIsID': typeof WatIsIDRoute
  '/project/$name': typeof ProjectNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/articles' | '/main' | '/watIsID' | '/project/$name'
  fileRoutesByTo: FileRoutesByTo
  to: '/articles' | '/main' | '/watIsID' | '/project/$name'
  id: '__root__' | '/articles' | '/main' | '/watIsID' | '/project/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ArticlesRoute: typeof ArticlesRoute
  MainRoute: typeof MainRoute
  WatIsIDRoute: typeof WatIsIDRoute
  ProjectNameRoute: typeof ProjectNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watIsID': {
      id: '/watIsID'
      path: '/watIsID'
      fullPath: '/watIsID'
      preLoaderRoute: typeof WatIsIDRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main': {
      id: '/main'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$name': {
      id: '/project/$name'
      path: '/project/$name'
      fullPath: '/project/$name'
      preLoaderRoute: typeof ProjectNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ArticlesRoute: ArticlesRoute,
  MainRoute: MainRoute,
  WatIsIDRoute: WatIsIDRoute,
  ProjectNameRoute: ProjectNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
